server:
  port: 8099 # 👈 On choisit 8099, totalement libre de tout projet !

spring:
  application:
    name: webapp

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
