server:
  port: 8083

spring:
  application:
    name: payment-service
  datasource:
    # ? On cible le port 3310. L'option 'createDatabaseIfNotExist=true'
    # va demander à MySQL de créer automatiquement la base 'payment_db' si elle n'existe pas.
    url: jdbc:mysql://localhost:3310/payment_db?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password  # ? Workbench
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true