server:
  port: 8082

spring:
  application:
    name: product-service

  # ─── CONFIGURATION CONSUL (ALIGNÉE SUR LE RÉSEAU) ───
  cloud:
    compatibility-verifier:
      enabled: false
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}-v4-${random.value}
        prefer-ip-address: true
        # 👇 Votre IP Wi-Fi physique pour que Consul (Docker) sorte vers IntelliJ
        ip-address: ${spring.cloud.client.ip-address}
        health-check-path: /actuator/health
        health-check-interval: 10s

  # ─── INITIALISATION SQL ───
  sql:
    init:
      mode: never

  # ─── CONFIGURATION BASE DE DONNÉES ET JPA ───
  datasource:
    url: jdbc:mysql://localhost:3310/cafe_velours_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# 👇 Exposition de l'Actuator pour le Health Check Consul
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always