server:
  port: 8083

spring:
  application:
    name: order-service

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:h2:mem:orderdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  # LA PROPRIÉTÉ COMPATIBILITÉ EST BIEN PLACÉE ICI (SOUS LE BLOC SPRING GLOBAL)
  cloud:
    compatibility-verifier:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true # 👈 Force Eureka à utiliser l'IP brute au lieu de .mshome.net