server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    compatibility-verifier:
      enabled: false

    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}-v4-${random.value}
        prefer-ip-address: true
        ip-address: 127.0.0.1

    # Nouvelle arborescence officielle Spring Boot 3.5+
    gateway:
      server:
        webflux:
          routes:
            - id: product-service-route
              uri: lb://product-service
              predicates:
                - Path=/api/products/**

            - id: order-service-route
              uri: lb://order-service
              predicates:
                - Path=/api/orders/** # <--- TOUTES LES REQUÊTES PANIER/COMMANDE PASSERONT PAR ICI
          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':
                allowedOriginPatterns: "*"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true